---@type table
local M = {}

---@type table
M.blockcomments = {
  html = { "<!-- ", " -->" },
  markdown = { "<!-- ", " -->" },
  ocaml = { "(* ", " *)" },
  css = { "/* ", " */" },
}

---@type table
M.comments = {
  ada = { "-- " },
  arduino = { "// " },
  automake = { "# " },
  awk = { "# " },
  bash = { "# " },
  c = { "// " },
  cs = { "// " },
  csh = { "# " },
  conf = { "# " },
  config = { "# " },
  confini = { "# " },
  clojure = { ";; " },
  d = { "// " },
  dart = { "// " },
  diff = { "# " },
  dockerfile = { "# " },
  elixir = { "# " },
  erlang = { "% " },
  fennel = { ";; " },
  gitattributes = { "# " },
  gitcommit = { "# " },
  gitconfig = { ";; " },
  gitignore = { "# " },
  gitrebase = { "# " },
  gdscript = { "# " },
  go = { "// " },
  groff = { [[\" ]] },
  haskell = { "-- " },
  i3config = { "# " },
  java = { "// " },
  javascript = { "// " },
  json = { "" },
  julia = { "# " },
  lisp = { ";; " },
  lua = { "-- " },
  m4 = { "dnl " },
  make = { "# " },
  objc = { "// " },
  pascal = { "// " },
  perl = { "# " },
  python = { "# " },
  ratpoison = { "# " },
  racket = { ";; " },
  ruby = { "# " },
  rust = { "// " },
  scala = { "// " },
  scheme = { ";; " },
  sh = { "# " },
  swayconfig = { "# " },
  swift = { "// " },
  sql = { "-- " },
  tex = { "% " },
  text = { "" },
  tcsh = { "# " },
  toml = { "# " },
  typescript = { "// " },
  vim = { [[" ]] },
  yaml = { "# " },
  zsh = { "# " },
}

return M
